import autth.PDA
import autth.leftmost_deriv
import Mathlib.Computability.ContextFreeGrammar
namespace PDA_to_CFG

/-!
# Equivalence of languages accepted by PDAs and languages generated by CFGs

This File contains the proof that the set of languages accepted by some
CFG is exactly the same as the set of languages generated by some PDA.

For the the direction of pda to grammar, we will first define such a
grammar and prove than that the languages are equal.
-/

-- In this whole section M will be the PDA we want to convert to a grammar

noncomputable section

variable {Q T S : Type} [Fintype Q] [Fintype T] [Fintype S]
    [DecidableEq Q][DecidableEq T][DecidableEq S]

variable {M : PDA Q T S}
--abbrev max_push (M : PDA Q T S)
open Symbol

inductive N (M: PDA Q T S)  where
  | start : N M
  | single : Q → S → Q → N M
  | list : Q → List S → Q → N M
deriving DecidableEq

instance : DecidableEq (ContextFreeRule T (N M)) := by
  intro ⟨n₁, α₁⟩ ⟨n₂, α₂⟩
  simp only [ContextFreeRule.mk.injEq]
  by_cases h₁ : n₁=n₂  <;>
  by_cases h₂ : α₁=α₂ <;> simp_all
  exact instDecidableTrue
  exact instDecidableFalse
  exact instDecidableFalse
  exact instDecidableFalse


abbrev epsilon_rule (q : Q): ContextFreeRule T (N M) := ⟨N.list q [] q ,[]⟩
abbrev compute_rule (q p q₁: Q) (a : T) (Z : S) (α : List S)
    (_ : (q₁, α) ∈ M.transition_fun q a Z): ContextFreeRule T (N M) :=
  ⟨N.single q Z p, [terminal a, nonterminal (N.list q₁ α p)]⟩
abbrev compute_rule' (q p q₁: Q) (Z : S) (α : List S)
    (_ : (q₁, α) ∈ M.transition_fun' q Z): ContextFreeRule T (N M) :=
  ⟨N.single q Z p, [nonterminal (N.list q₁ α p)]⟩
abbrev split_rule (q q₁ p: Q)(Z : S)(α : List S) : ContextFreeRule T (N M) :=
  ⟨N.list q (Z::α) p, [nonterminal (N.single q Z q₁),nonterminal (N.list q₁ α p)]⟩
abbrev start_rule (q p: Q): ContextFreeRule T (N M) :=
  ⟨N.start, [nonterminal (N.single p M.start_symbol q)]⟩

#check (Finset.univ : Finset Q)

abbrev epsilon_rules : List (ContextFreeRule T (N M)) := (Finset.univ.image epsilon_rule).toList
