import autth.PDA
import autth.leftmost_deriv
import autth.CountingStepsLeftmost
import Mathlib.Computability.ContextFreeGrammar
import Mathlib.Data.Set.Finite
namespace PDA_to_CFG

/-!
# Equivalence of languages accepted by PDAs and languages generated by CFGs

This File contains the proof that the set of languages accepted by some
CFG is exactly the same as the set of languages generated by some PDA.

For the the direction of pda to grammar, we will first define such a
grammar and prove than that the languages are equal.
-/

-- In this whole section M will be the PDA we want to convert to a grammar

noncomputable section

variable {Q T S : Type} [Fintype Q] [Fintype T] [Fintype S]

variable {M : PDA Q T S}

--abbrev max_push (M : PDA Q T S)
open Symbol
open PDA
open ContextFreeGrammar

abbrev AllStackPushes (M : PDA Q T S) : Set (List S) :=
  (Prod.snd '' ⋃(q : Q)(a : T)(Z : S), M.transition_fun q a Z) ∪
  Prod.snd '' ⋃(q : Q)(Z : S), M.transition_fun' q Z

theorem allStackPushes_finite (M : PDA Q T S) : (AllStackPushes M).Finite := by
  rw [AllStackPushes]
  rw [Set.finite_union]
  refine ⟨?_,?_⟩
  · let A := ⋃(q : Q)(a : T)(Z : S), M.transition_fun q a Z
    have a_finite : A.Finite := by
      apply Set.finite_iUnion
      intro q
      apply Set.finite_iUnion
      intro a
      apply Set.finite_iUnion
      intro Z
      exact M.finite q a Z
    let B := Prod.snd '' A
    have b_finite : B.Finite := by
      apply Set.Finite.image
      exact a_finite
    simp_all
  · let A := ⋃(q : Q)(Z : S), M.transition_fun' q Z
    have a_finite : A.Finite := by
      apply Set.finite_iUnion
      intro q
      apply Set.finite_iUnion
      intro Z
      exact M.finite' q Z
    let B := Prod.snd '' A
    have b_finite : B.Finite := by
      apply Set.Finite.image
      exact a_finite
    simp_all

abbrev AllStackPushes' (M : PDA Q T S): Finset (List S) :=
  (allStackPushes_finite M).toFinset

abbrev max_push (M : PDA Q T S)  := max ((AllStackPushes' M).image (λ α ↦ α.length)).max 1

inductive N (M: PDA Q T S)  where
  | start : N M
  | single : Q → S → Q → N M
  | list : Q → List S  → Q → N M

abbrev N.IsAllowed: N M → Prop
  | N.start => True
  | N.single _ _ _ => True
  | N.list _ α _ => α.length ≤ max_push M

abbrev AllowedNonterminals : Set (N M) := {n : N M | n.IsAllowed}

theorem allowedNonterminal_finite : (AllowedNonterminals : Set (N M)).Finite  := by
  let S₁ : Set (N M) := ⋃ (q : Q)(Z : S)(p : Q), {N.single q Z p}
  let S₂ : Set (List S) := {α : List S | α.length  ≤ max_push M}
  let S₃ : Set (N M) := ⋃ (q : Q)(p : Q)(α ∈ S₂), {N.list q α p}
  have h_s₁ : S₁.Finite := by
    dsimp [S₁]
    repeat (apply Set.finite_iUnion; intro)
    apply Set.finite_singleton
  have h_s₂ : S₂.Finite := by
    dsimp [S₂]
    induction' max_push M using WithBot.recBotCoe with n
    · simp
    · convert_to {α : List S| α.length ≤ n}.Finite
      · ext
        simp [Set.mem_setOf_eq]
        convert WithBot.coe_le_coe
      · apply List.finite_length_le
  have h_s₃ : S₃.Finite := by
    repeat (apply Set.finite_iUnion; intro)
    apply Set.Finite.biUnion h_s₂
    intros
    apply Set.finite_singleton
  have h_u : (S₁ ∪ S₃ ∪ {N.start}).Finite := by
    repeat rw [Set.finite_union]
    exact ⟨⟨h_s₁, h_s₃⟩, Set.finite_singleton _⟩
  have : AllowedNonterminals ⊆ S₁ ∪ S₃ ∪ {N.start} := by
    intro n hn
    rcases n with _|⟨q,Z,p⟩|⟨q,α,p⟩
    · rw [Set.mem_union]
      right
      rfl
    · repeat rw [Set.mem_union]
      left
      left
      repeat rw [Set.mem_iUnion]
      use q
      rw [Set.mem_iUnion]
      use Z
      rw [Set.mem_iUnion]
      use p
      rfl
    · repeat rw [Set.mem_union]
      left
      right
      rw [Set.mem_setOf] at hn
      dsimp [N.IsAllowed] at hn
      have hα : α ∈ S₂ := by rw [Set.mem_setOf]; exact hn
      rw [Set.mem_iUnion₂]
      use q, p
      apply Set.mem_biUnion hα
      rfl
  exact Set.Finite.subset h_u this

theorem push_le_max_push (α : List S)(q : Q)(Z : S)(a : T)
    (h : α ∈ Prod.snd '' M.transition_fun q a Z): α.length ≤ max_push M := by
  rw [max_push]
  apply le_max_of_le_left
  apply Finset.le_max
  rw [Finset.mem_image]
  use α
  refine ⟨?_, by simp⟩
  rw [Set.Finite.mem_toFinset]
  rw [Set.mem_union]
  left
  have :  M.transition_fun q a Z ⊆  ⋃ q, ⋃ a, ⋃ Z, M.transition_fun q a Z := by
    intro x hx
    simp only [Set.mem_iUnion]
    use q, a, Z
  have  := Set.image_subset Prod.snd this
  apply Set.mem_of_subset_of_mem this
  exact h

theorem push_le_max_push' (α : List S)(q : Q)(Z : S)
    (h : α ∈ Prod.snd '' M.transition_fun' q Z): α.length ≤ max_push M := by
  rw [max_push]
  apply le_max_of_le_left
  apply Finset.le_max
  rw [Finset.mem_image]
  use α
  refine ⟨?_, by simp⟩
  rw [Set.Finite.mem_toFinset]
  rw [Set.mem_union]
  right
  have : M.transition_fun' q Z ⊆  ⋃ q, ⋃ Z, M.transition_fun' q Z := by
    intro x hx
    simp only [Set.mem_iUnion]
    use q, Z
  have  := Set.image_subset Prod.snd this
  apply Set.mem_of_subset_of_mem this
  exact h

abbrev epsilon_rule (q : Q): Set (ContextFreeRule T (N M)) := {⟨N.list q [] q ,[]⟩}

abbrev compute_rule (q p: Q) (a : T) (Z : S) : Set (ContextFreeRule T (N M)) :=
  (λ ⟨q₁,α⟩ ↦ ⟨N.single q Z p, [terminal a, nonterminal (N.list q₁ α p)]⟩) '' M.transition_fun q a Z

abbrev compute_rule' (q p: Q) (Z : S) : Set (ContextFreeRule T (N M)) :=
  (λ ⟨q₁,α⟩ ↦ ⟨N.single q Z p, [nonterminal (N.list q₁ α p)]⟩) '' M.transition_fun' q Z

abbrev split_rule (q₁:Q) :(n : N M) →  Set (ContextFreeRule T (N M))
  | N.start => ∅
  | N.single _ _ _=> ∅
  | N.list _ [] _ => ∅
  | N.list q (Z::α)  p =>
    {⟨N.list q (Z::α) p, [nonterminal (N.single q Z q₁),nonterminal (N.list q₁ α p)]⟩}

abbrev start_rule (q p: Q): Set (ContextFreeRule T (N M)) :=
  {⟨N.start, [nonterminal (N.single p M.start_symbol q)]⟩}

abbrev RuleSet : Set (ContextFreeRule T (N M)) :=
  (⋃q:Q,  epsilon_rule q) ∪ (⋃(q:Q)(p:Q)(a:T)(Z:S), compute_rule q p a Z)
  ∪ (⋃(q:Q)(p:Q)(Z:S), compute_rule' q p Z) ∪ (⋃(q:Q)(n ∈ AllowedNonterminals), split_rule q n)

theorem ruleSet_finite : (RuleSet : Set (ContextFreeRule T (N M))).Finite := by
  dsimp [RuleSet]
  repeat rw [Set.finite_union]
  simp only [and_assoc]
  refine ⟨?_, ?_, ?_, ?_⟩
  · apply Set.finite_iUnion
    intro q
    dsimp [epsilon_rule]
    apply Set.finite_singleton
  · repeat (apply Set.finite_iUnion; intro)
    dsimp [compute_rule]
    apply Set.Finite.image
    apply M.finite
  · repeat (apply Set.finite_iUnion; intro)
    dsimp [compute_rule]
    apply Set.Finite.image
    apply M.finite'
  · apply Set.finite_iUnion
    intro
    apply Set.Finite.biUnion allowedNonterminal_finite
    intro n hn
    rcases n with _|_|⟨_,_|_,_⟩ <;> dsimp [split_rule] <;> simp

abbrev rules : Finset (ContextFreeRule T (N M)) := ruleSet_finite.toFinset

abbrev G (M : PDA Q T S) : ContextFreeGrammar T := {
  NT := N M
  initial := N.start
  rules := rules
}

theorem produces_epsilon (q : Q) :
    (G M).Produces [nonterminal (N.list q [] q)] (List.map terminal []) := by
  let r : ContextFreeRule T (N M) := ⟨N.list q [] q ,[]⟩
  have hr : r ∈ (G M).rules  := by
    rw [Set.Finite.mem_toFinset]
    simp only [RuleSet,Set.mem_union]
    repeat left
    rw [Set.mem_iUnion]
    use q
    simp [r]
  use r, hr
  rw [List.map_nil]
  simp [ContextFreeRule.rewrites_iff]

theorem produces_split (q q₁ p : Q){α : List S}{Z : S}(h : (Z :: α).length ≤ max_push M ):
    (G M).Produces [nonterminal (N.list q (Z :: α) p)]
    [nonterminal (N.single q Z q₁), nonterminal (N.list q₁ α p)] := by
  let r : ContextFreeRule T (N M) :=
    ⟨N.list q (Z::α) p, [nonterminal (N.single q Z q₁),nonterminal (N.list q₁ α p)]⟩
  have hr : r ∈ (G M).rules := by
    simp only [Set.Finite.mem_toFinset, Set.mem_union]
    repeat right
    simp only [Set.mem_iUnion]
    use q₁, N.list q (Z :: α) p
    refine ⟨?_,?_⟩
    · rw [Set.mem_setOf]
      simp only [N.IsAllowed, h]
    · simp only [split_rule, Set.mem_singleton, r]
  use r, hr
  rw [ContextFreeRule.rewrites_iff]
  use [], []
  simp

theorem produces_compute {q q₁ p : Q}{α : List S}{a : T}{Z : S}
    (h : (q₁, α) ∈ M.transition_fun q a Z) :
    (G M).Produces [nonterminal (N.single q Z p)] [terminal a, nonterminal (N.list q₁ α p)] := by
  let r : ContextFreeRule T (N M) := ⟨N.single q Z p, [terminal a, nonterminal (N.list q₁ α p)]⟩
  have hr : r  ∈ (G M).rules := by
    simp only [Set.Finite.mem_toFinset, Set.mem_union]
    left
    left
    right
    simp only [Set.mem_iUnion]
    use q, p, a, Z
    simp only [Set.mem_image]
    use (q₁, α)
  use r, hr
  rw [ContextFreeRule.rewrites_iff]
  use [], []
  simp

theorem produces_compute' {q q₁ p : Q}{α : List S}{Z : S}
    (h : (q₁, α) ∈ M.transition_fun' q Z) :
    (G M).Produces [nonterminal (N.single q Z p)] [nonterminal (N.list q₁ α p)] := by
  let r : ContextFreeRule T (N M) := ⟨N.single q Z p, [nonterminal (N.list q₁ α p)]⟩
  have hr : r  ∈ (G M).rules := by
    simp only [Set.Finite.mem_toFinset, Set.mem_union]
    left
    right
    simp only [Set.mem_iUnion]
    use q, p, Z
    simp only [Set.mem_image]
    use (q₁, α)
  use r, hr
  rw [ContextFreeRule.rewrites_iff]
  use [], []
  simp

theorem derives_of_reachesIn {γ : List S}{q p : Q}{x : List T}{n : ℕ}
    (hγ : γ.length ≤ max_push M) (h : M.ReachesIn n ⟨q,x,γ⟩ ⟨p,[],[]⟩) :
    (G M).Derives [nonterminal (N.list q γ p)] (x.map terminal) := by
  induction' n using Nat.strong_induction_on with n ih generalizing x γ p q
  rcases n with _ | ⟨n⟩
  · apply reachesIn_zero at h
    injection h with h₁ h₂ h₃
    rw [h₁,h₂,h₃]
    apply Produces.single
    exact produces_epsilon _
  · rcases γ with _ | ⟨Z, γ⟩
    · have := reaches_iff_reachesIn.mpr ⟨n+1, h⟩
      obtain ⟨rfl,_,rfl⟩:= reaches_on_empty_stack  this
      apply Produces.single
      exact produces_epsilon _
    · obtain ⟨⟨q₀, x, γ'⟩, h₁, h₂⟩ := reachesIn_iff_split_first.mpr h
      rw [←reaches₁_iff_reachesIn_one] at h₁
      rcases reaches₁_push h₁ with ⟨a, y, q₁, α, rfl, hc, hα⟩ | ⟨q₁, α, hc, hα⟩
      · obtain ⟨rfl, rfl, rfl⟩ := conf.mk.inj hc
        obtain ⟨q₁, m₁, m₂, y₁, y₂, hy, hm₁, hm₂, h₂₁, h₂₂⟩ := split_stack h₂
        have hα_allowed : α.length ≤ max_push M  := by
          apply push_le_max_push
          rw [Set.mem_image]
          use (q₀, α)
        have hγ_allowed : γ.length ≤ max_push M  := by
          rw [List.length_cons] at hγ
          have := WithBot.coe_le_coe.mpr (by linarith : γ.length ≤ γ.length + 1)
          apply le_trans
          exact this
          exact hγ
        apply ih m₁ (Nat.lt_succ_of_le hm₁) hα_allowed at h₂₁
        apply ih m₂ (Nat.lt_succ_of_le hm₂) hγ_allowed at h₂₂
        convert calc
          (G M).Derives
            [nonterminal (N.list q (Z :: γ) p)]
            ([nonterminal (N.single q Z q₁)]++[nonterminal (N.list q₁ γ p)]) := by
              exact (produces_split q q₁ p hγ).single
          (G M).Derives _
            ([terminal a, nonterminal (N.list q₀ α q₁)]++[nonterminal (N.list q₁ γ p)]) := by
              apply Derives.append_right
              exact (produces_compute hα).single
          (G M).Derives _
             ([terminal a, nonterminal (N.list q₀ α q₁)]++ (List.map terminal y₂)) := by
              apply Derives.append_left
              exact h₂₂
          (G M).Derives _
            ([terminal a] ++ List.map terminal y₁++ (List.map terminal y₂)) := by
            apply Derives.append_right
            change (G M).Derives
              ([terminal a] ++ [nonterminal (N.list q₀ α q₁)])
              ([terminal a] ++ List.map terminal y₁)
            apply Derives.append_left
            exact h₂₁
        simp [hy]
      · obtain ⟨rfl, rfl, rfl⟩ := conf.mk.inj hc
        obtain ⟨q₁, m₁, m₂, y₁, y₂, hy, hm₁, hm₂, h₂₁, h₂₂⟩ := split_stack h₂
        have hα_allowed : α.length ≤ max_push M  := by
          apply push_le_max_push'
          rw [Set.mem_image]
          use (q₀, α)
        have hγ_allowed : γ.length ≤ max_push M  := by
          rw [List.length_cons] at hγ
          have := WithBot.coe_le_coe.mpr (by linarith : γ.length ≤ γ.length + 1)
          apply le_trans
          exact this
          exact hγ
        apply ih m₁ (Nat.lt_succ_of_le hm₁) hα_allowed at h₂₁
        apply ih m₂ (Nat.lt_succ_of_le hm₂) hγ_allowed at h₂₂
        convert calc
          (G M).Derives
            [nonterminal (N.list q (Z :: γ) p)]
            ([nonterminal (N.single q Z q₁)]++[nonterminal (N.list q₁ γ p)]) := by
              exact (produces_split q q₁ p hγ).single
          (G M).Derives _
            ([nonterminal (N.list q₀ α q₁)]++[nonterminal (N.list q₁ γ p)]) := by
              apply Derives.append_right
              exact (produces_compute' hα).single
          (G M).Derives _
             ([nonterminal (N.list q₀ α q₁)] ++ (List.map terminal y₂)) := by
              apply Derives.append_left
              exact h₂₂
          (G M).Derives _
            ( List.map terminal y₁++ (List.map terminal y₂)) := by
            apply Derives.append_right
            exact h₂₁
        simp [hy]

theorem derivation_empty {n : ℕ}{x : List T}{q p : Q}
    (h : (G M).DerivesLeftmostIn [nonterminal (N.list q [] p)] (List.map terminal x) n) :
    q = p ∧ x = [] := by
  rcases n with _|⟨n⟩
  · have := h.zero
    cases x <;> simp at this
  · obtain ⟨v,h₁, h₂⟩ := h.head_of_succ
    simp only [ProducesLeftmost] at h₁
    obtain ⟨r, hr, h₁⟩ := h₁
    simp only [Set.Finite.mem_toFinset, Set.mem_union, or_assoc] at hr
    rcases hr with hr | hr | hr | hr
    · simp only [Set.mem_iUnion] at hr
      obtain ⟨q₀, hr⟩ := hr
      simp only [epsilon_rule, Set.mem_singleton_iff] at hr
      rw [hr] at h₁
      rw [ContextFreeRule.RewritesLeftmost.rewrites_leftmost_iff] at h₁
      obtain ⟨u₁, u₂, h₁, h₁'⟩ := h₁
      dsimp only at h₁ h₂
      cases u₁
      · cases u₂
        · change v = [] at h₁'
          simp only [h₁'] at *
          apply derivesLeftmostIn_empty at h₂
          simp_all
        · simp_all
      · simp_all
    · simp only [Set.mem_iUnion] at hr
      obtain ⟨q₀, p₀, a, Z, hr⟩ := hr
      simp only [compute_rule, Set.mem_image] at hr
      obtain ⟨q₁, α, hr⟩ := hr
      rw [hr.symm] at h₁
      simp only [ContextFreeRule.RewritesLeftmost.rewrites_leftmost_iff] at h₁
      obtain ⟨p, q, h₁⟩ := h₁
      cases p <;> simp at h₁
    · simp only [Set.mem_iUnion] at hr
      obtain ⟨q₀, p₀, Z, hr⟩ := hr
      simp only [compute_rule', Set.mem_image] at hr
      obtain ⟨q₁, α, hr⟩ := hr
      rw [hr.symm] at h₁
      simp only [ContextFreeRule.RewritesLeftmost.rewrites_leftmost_iff] at h₁
      obtain ⟨p, q, h₁⟩ := h₁
      cases p <;> simp at h₁
    · simp only [Set.mem_iUnion] at hr
      obtain ⟨q₀, n, hr⟩ := hr
      obtain ⟨hn, hr⟩ := hr
      simp only [split_rule] at hr
      rcases n with _ | _ | ⟨q₁, _|⟨Z,α⟩, p₁⟩
      · simp_all
      · simp_all
      · simp_all
      · dsimp at hr
        rw [Set.mem_singleton_iff] at hr
        rw [hr, ContextFreeRule.RewritesLeftmost.rewrites_leftmost_iff] at h₁
        obtain ⟨p₁, q₁, h₁⟩ := h₁
        cases p₁ <;> simp_all

theorem reachesIn_of_derivesLeftmostIn {γ : List S}{q p : Q}{x : List T}{n : ℕ}
    (hγ : γ.length ≤ max_push M)
    (h : (G M).DerivesLeftmostIn [nonterminal (N.list q γ p)] (x.map terminal) n) :
    M.Reaches ⟨q, x, γ⟩ ⟨p, [], []⟩ := by
  induction' n using Nat.strong_induction_on with n ih
  · cases γ
    · apply derivation_empty at h
      simp only [h]
      rfl
    · rcases n with _ | ⟨n⟩
      · obtain h := h.zero
        cases x <;> simp at h
      · obtain ⟨u, h₁, h₂⟩ := h.head_of_succ
