import autth.PDA
import autth.leftmost_deriv
import Mathlib.Computability.ContextFreeGrammar
import Mathlib.Data.Set.Finite
namespace PDA_to_CFG

/-!
# Equivalence of languages accepted by PDAs and languages generated by CFGs

This File contains the proof that the set of languages accepted by some
CFG is exactly the same as the set of languages generated by some PDA.

For the the direction of pda to grammar, we will first define such a
grammar and prove than that the languages are equal.
-/

-- In this whole section M will be the PDA we want to convert to a grammar

noncomputable section

variable {Q T S : Type} [Fintype Q] [Fintype T] [Fintype S]
    [DecidableEq Q][DecidableEq T][DecidableEq S]

variable {M : PDA Q T S}
variable (h_M_not_trivial : ((⋃(q : Q)(a : T)(Z : S), M.transition_fun q a Z) ∪
  (⋃(q : Q)(Z : S), M.transition_fun' q Z)).Nonempty)
--abbrev max_push (M : PDA Q T S)
open Symbol

instance : DecidableEq (ContextFreeRule T (N M)) := by
  intro ⟨n₁, α₁⟩ ⟨n₂, α₂⟩
  simp only [ContextFreeRule.mk.injEq]
  by_cases h₁ : n₁=n₂  <;>
  by_cases h₂ : α₁=α₂ <;> simp_all
  exact instDecidableTrue
  exact instDecidableFalse
  exact instDecidableFalse
  exact instDecidableFalse

abbrev AllStackPushes (M : PDA Q T S) : Set (List S) :=
  (Prod.snd '' ⋃(q : Q)(a : T)(Z : S), M.transition_fun q a Z) ∪
  Prod.snd '' ⋃(q : Q)(Z : S), M.transition_fun' q Z

theorem allStackPushes_finite (M : PDA Q T S): (AllStackPushes M).Finite := by
  rw [AllStackPushes]
  rw [Set.finite_union]
  refine ⟨?_,?_⟩
  · let A := ⋃(q : Q)(a : T)(Z : S), M.transition_fun q a Z
    have a_finite : A.Finite := by
      apply Set.finite_iUnion
      intro q
      apply Set.finite_iUnion
      intro a
      apply Set.finite_iUnion
      intro Z
      exact M.finite q a Z
    let B := Prod.snd '' A
    have b_finite : B.Finite := by
      apply Set.Finite.image
      exact a_finite
    simp_all
  · let A := ⋃(q : Q)(Z : S), M.transition_fun' q Z
    have a_finite : A.Finite := by
      apply Set.finite_iUnion
      intro q
      apply Set.finite_iUnion
      intro Z
      exact M.finite' q Z
    let B := Prod.snd '' A
    have b_finite : B.Finite := by
      apply Set.Finite.image
      exact a_finite
    simp_all

abbrev max_push (M : PDA Q T S) : ℕ :=
  ((allStackPushes_finite M).image (λ α ↦ α.length)).toFinset.max.unbot' 1


inductive AllowedString (M : PDA Q T S) : (List S) → Prop where
  | base (γ : List S)(h : γ ∈ AllStackPushes M) : AllowedString M γ
  | step (a : S)(γ : List S)(h : AllowedString M (a::γ)) : AllowedString M γ

inductive N (M: PDA Q T S)  where
  | start : N M
  | single : Q → S → Q → N M
  | list : Q → List S → Q → N M

abbrev UseNonterminal : N M → Prop
  | N.start => True
  | N.single _ _ _ => True
  | N.list _ α _ => α.length ≤ max_push M

abbrev UsedNonterminals := {n : N M | UseNonterminal n}

abbrev epsilon_rule (q : Q): ContextFreeRule T (N M) := ⟨N.list q [] q ,[]⟩

abbrev compute_rule (q p: Q) (a : T) (Z : S) : Set (ContextFreeRule T (N M)) :=
  (λ ⟨q₁,α⟩ ↦ ⟨N.single q Z p, [terminal a, nonterminal (N.list q₁ α p)]⟩) '' M.transition_fun q a Z

abbrev compute_rule' (q p: Q) (Z : S) : Set (ContextFreeRule T (N M)) :=
  (λ ⟨q₁,α⟩ ↦ ⟨N.single q Z p, [nonterminal (N.list q₁ α p)]⟩) '' M.transition_fun' q Z

abbrev split_rule (q₁:Q) :(n : N M) →  Set (ContextFreeRule T (N M))
  | N.start => ∅
  | N.single _ _ _=> ∅
  | N.list _ [] _ => ∅
  | N.list p (Z::α)  q =>
    {⟨N.list q (Z::α) p, [nonterminal (N.single q Z q₁),nonterminal (N.list q₁ α p)]⟩}

abbrev start_rule (q p: Q): Set (ContextFreeRule T (N M)) :=
  {⟨N.start, [nonterminal (N.single p M.start_symbol q)]⟩}

#check (Finset.univ : Finset Q)

abbrev epsilon_rules : List (ContextFreeRule T (N M)) := (Finset.univ.image epsilon_rule).toList
